#!/bin/bash
cd Tests
cd lib
echo "Install gtest lib.............."
git clone https://github.com/google/googletest.git -b release-1.12.1
cd googletest        # Main directory of the cloned repository.
mkdir build          # Create a directory to hold the build output.
cd build
cmake ..             # Generate native build scripts for GoogleTest.
echo "build current proj"
cd ../../../../
mkdir build
cd build
cmake ..
make
cd .